name: Release stage 1 - create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (PEP 440 compliant e.g., 1.12.4, 5.0a2 etc)'
        required: true
      branch:
        description: 'The branch to open the PR against'
        required: false
        default: 'master'

env:
  # Best not to include the GH token here, only do it for the steps that need it
  # PYPI_PACKAGE_NAME: 'metomi-isodatetime'
  # REPOSITORY: ${{ github.repository }}
  # INIT_FILE: 'metomi/isodatetime/__init__.py'
  # CHANGELOG_FILE: CHANGES.md
  # PR_BRANCH_PREFIX: 'prepare-'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Sanitise workflow inputs # Should be first step
      shell: node {0}
      env:
        VERSION: ${{ github.event.inputs.version }}
        BRANCH: ${{ github.event.inputs.branch }}
      run: |
        const versionStr = process.env.VERSION.trim();
        console.log(`::set-env name=VERSION::${versionStr}`);
        const branchStr = process.env.BRANCH.trim();
        console.log(`::set-env name=BASE_REF::${branchStr}`);

    - name: Checkout repo
      uses: actions/checkout@v2.3.1
      with:
        ref: ${{ env.BASE_REF }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create & checkout PR branch
      uses: MetRonnie/test-action/checkout-pr-branch@master

    - name: Set the package version
      uses: MetRonnie/test-action/set-python-package-version@master
      with:
        init-file: 'metomi/isodatetime/__init__.py'
        pypi-package-name: 'metomi-isodatetime'

    - name: Update "released on" date in changelog
      continue-on-error: true
      uses: MetRonnie/test-action/update-changelog-release-date@master
      with:
        changelog-file: CHANGES.md

    - name: Test the build
      uses: MetRonnie/test-action/build-python-package@master
      with:
        dry-run: true

    - name: Commit & push
      id: push
      uses: MetRonnie/test-action/commit-push@master

    - name: Create pull request
      uses: MetRonnie/test-action/create-release-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: (On fail) Delete failed PR branch on origin, if it was pushed
    #   if: always() && steps.create-pr.outcome != 'success' && steps.push.outcome == 'success'
    #     # Need status check function in if-condition otherwise won't run on fail
    #   run: |
    #     backup_sha=$( git rev-parse "origin/${HEAD_REF}" )
    #     git push -d origin "$HEAD_REF"
    #     echo "::warning:: Deleted the newly-pushed branch '${HEAD_REF}' because the workflow failed"
    #     echo "If you need to recover the branch:"
    #     echo "  git fetch origin ${backup_sha}"
    #     echo "  git checkout -b ${HEAD_REF} ${backup_sha}"
