name: Release stage 1 - create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number (PEP 440 compliant e.g., 1.12.4, 5.0a2 etc)
        required: true
      branch:
        description: The branch to open the PR against
        required: false
        default: 'master'

# env:
  # Best not to include the GH token here, only do it for the steps that need it
  # PYPI_PACKAGE_NAME: 'metomi-isodatetime'
  # REPOSITORY: ${{ github.repository }}
  # INIT_FILE: 'metomi/isodatetime/__init__.py'
  # CHANGELOG_FILE: CHANGES.md
  # PR_BRANCH_PREFIX: 'prepare-'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Sanitise workflow inputs # Should be 1st step
      uses: MetRonnie/test-action/sanitize-inputs@master

    - name: Checkout repo
      uses: actions/checkout@v2.3.1
      with:
        ref: ${{ env.BASE_REF }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create & checkout PR branch
      uses: MetRonnie/test-action/checkout-pr-branch@master

    - name: Set the package version
      uses: MetRonnie/test-action/set-python-package-version@master
      with:
        init-file: 'metomi/isodatetime/__init__.py'
        pypi-package-name: 'metomi-isodatetime'

    - name: Update "released on" date in changelog
      continue-on-error: true
      uses: MetRonnie/test-action/update-changelog-release-date@master
      with:
        changelog-file: CHANGES.md

    - name: Test the build
      uses: MetRonnie/test-action/build-python-package@master
      with:
        dry-run: true

    - name: Create pull request
      uses: MetRonnie/test-action/create-release-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
