name: Testing stuff out

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Version number (PEP 440 compliant e.g., 1.12.4, 5.0a2 etc)'
    #     required: true
    #   branch:
    #     description: 'The branch to open the PR against'
    #     required: false
    #     default: 'master'

# env:
  # # Best not to include the GH token here, only do it for the steps that need it
  # PYPI_PACKAGE_NAME: 'metomi-isodatetime'
  # REPOSITORY: ${{ github.repository }}
  # INIT_FILE: 'metomi/isodatetime/__init__.py'
  # CHANGELOG_FILE: CHANGES.md
  # PR_BRANCH_PREFIX: 'prepare-'

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v2.3.1
      with:
        ref: ${{ env.BASE_REF }}

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: echo "$PWD"

    - uses: MetRonnie/test-action@master

    - run: echo "$GENNARO"

    - shell: python
      run: |
        import packaging.version as ver
        foo = ver.Version('1.0a3')
        print(foo)

    - run: cmp_py_versions_b 1.0 1.1
