name: Testing stuff out

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Version number (PEP 440 compliant e.g., 1.12.4, 5.0a2 etc)'
    #     required: true
    #   branch:
    #     description: 'The branch to open the PR against'
    #     required: false
    #     default: 'master'

# env:
  # # Best not to include the GH token here, only do it for the steps that need it
  # PYPI_PACKAGE_NAME: 'metomi-isodatetime'
  # REPOSITORY: ${{ github.repository }}
  # INIT_FILE: 'metomi/isodatetime/__init__.py'
  # CHANGELOG_FILE: CHANGES.md
  # PR_BRANCH_PREFIX: 'prepare-'

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: actions/checkout@v2

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          branch_name="alan-wake"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

          git checkout -b "$branch_name"
          echo "Turn the light on" > departure.txt

          git add -A
          git commit -a -m "Chapter 1"
          git push origin "$branch_name"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -H "authorization: Bearer ${GH_TOKEN}" \
            -H 'content-type: application/json' \
            --data '{
              "title": "Auto PR: update copyright year",
              "head": "${{ env.BRANCH_NAME }}",
              "base": "master",
              "body": "Happy new year!"
            }'
